//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TssPreview.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TssPreview.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;magic&quot;:&quot;Tactical Sailing Simulator by Rinrab&quot;,&quot;version&quot;:1,&quot;marks&quot;:[{&quot;x&quot;:12.5,&quot;y&quot;:28,&quot;type&quot;:0},{&quot;x&quot;:27.5,&quot;y&quot;:28,&quot;type&quot;:1},{&quot;x&quot;:20,&quot;y&quot;:2,&quot;type&quot;:2}],&quot;width&quot;:40,&quot;height&quot;:30,&quot;wind&quot;:[0,10,0,0,0,5,0,5,5,0,5,0,5,5,0,-10,-10,-15,0,10,-5,-5,-15,-15,-5,-15,-15,-20,-15,-20,-20,-15,-20,-20,-20,-20,-15,-10,-10,-20,-20,-20,-15,-20,-20,-20,-15,-5,-5,-5],&quot;turncount&quot;:34,&quot;isStart&quot;:false,&quot;name&quot;:&quot;Random&quot;,&quot;players&quot;:[{&quot;x&quot;:21.37826015445413,&quot;y&quot;:2.642693264951851,&quot;rotation&quot;:-64.99999999999999,&quot;tack&quot;:false,&quot;color&quot;:&quot;red&quot;,&quot;name&quot;:&quot;Pl [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Demo1 {
            get {
                return ResourceManager.GetString("Demo1", resourceCulture);
            }
        }
    }
}
